### ISSUE TITLE
[11.1] Install br_account take long time in database with account_invoice

### ISSUE THREAD

**Issue by ghost** [Trust-Code/odoo-brasil#667]
Hi @danimaribeiro ,
I need your help with br_account installation in database with large number of invoices (about 2000) because it's take long time, more than 5 - 6 hours. 
I've reviewed the postgresql activity and I've viewed values of account_invoice / account_inovice_line fields are committing one by one instead of in group but I'm not sure this is the problem.
I don't have experience adding many fields at once so have any idea to improve the time of the installation?

Thanks!!

**Comment by danimaribeiro** [comment]
Generally the problem in this case is code that in write changes some values that trigger other onchanges.
Is pretty hard to spot the problem.

For example:
onchange defined in a field of account.invoice that goes over the list of lines and update values in lines, and then odoo needs to recompute the total values because invoice lines were changed.
This generate some recursivity that is not showing because in onchanges Odoo framework prevents to happen, but it slows down performance.


Other workaround more simple, is to comment the code _compute from localization, install and after update the code. After that if you do want to calculate ou can create a acttion server and calculate in batches.

**Comment by ghost** [comment]
Thank very much for your help!
During installation of br_account module I could see that this sentence was execute in database ->

UPDATE "account_invoice" SET "reconciled"=false,"residual"='XXX',"residual_signed"='XXX',"residual_company_signed"='XXX',"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (XXX);

I found only one method that write changes in that values ->

https://github.com/odoo/odoo/blob/879a7194788bf36b60dacfc4902a7cf02f21bbe7/addons/account/models/account_invoice.py#L101-L124

I commented depends decorator of this method:

![image](https://user-images.githubusercontent.com/12764560/49092359-279b3500-f262-11e8-9cfb-15621825c9ba.png)

The installation was done in 20 min instead of 5 - 6 hours.
